import pygame
import sys
import numpy as np

# set default display screen dimensions
WINDOW_HEIGHT = 576
WINDOW_WIDTH = 704
CELL_HEIGHT, CELL_WIDTH = (64, 64)

# set columns choice section default coordinates
COLUMNS_CHOICE = []
for i in range(2, 9):
    COLUMNS_CHOICE.append((CELL_WIDTH * i, CELL_HEIGHT))

# set default board
GAME_BOARD = [[] for i in range(7)]

# set default check for winner board
WINNER_BOARD = [[" " for i in range(6)] for i in range(7)]

# set default coordinates
COORDINATES = [[(CELL_WIDTH*2, CELL_HEIGHT*7), (CELL_WIDTH*2, CELL_HEIGHT*6), (CELL_WIDTH*2, CELL_HEIGHT*5), (CELL_WIDTH*2, CELL_HEIGHT*4), (CELL_WIDTH*2, CELL_HEIGHT*3), (CELL_WIDTH*2, CELL_HEIGHT*2)], [(CELL_WIDTH*3, CELL_HEIGHT*7), (CELL_WIDTH*3, CELL_HEIGHT*6), (CELL_WIDTH*3, CELL_HEIGHT*5), (CELL_WIDTH*3, CELL_HEIGHT*4), (CELL_WIDTH*3, CELL_HEIGHT*3), (CELL_WIDTH*3, CELL_HEIGHT*2)], [(CELL_WIDTH*4, CELL_HEIGHT*7), (CELL_WIDTH*4, CELL_HEIGHT*6), (CELL_WIDTH*4, CELL_HEIGHT*5), (CELL_WIDTH*4, CELL_HEIGHT*4), (CELL_WIDTH*4, CELL_HEIGHT*3), (CELL_WIDTH*4, CELL_HEIGHT*2)], [(CELL_WIDTH*5, CELL_HEIGHT*7), (CELL_WIDTH*5, CELL_HEIGHT*6), (CELL_WIDTH*5, CELL_HEIGHT*5), (CELL_WIDTH*5, CELL_HEIGHT*4), (CELL_WIDTH*5, CELL_HEIGHT*3), (CELL_WIDTH*5, CELL_HEIGHT*2)], [(CELL_WIDTH*6, CELL_HEIGHT*7), (CELL_WIDTH*6, CELL_HEIGHT*6), (CELL_WIDTH*6, CELL_HEIGHT*5), (CELL_WIDTH*6, CELL_HEIGHT*4), (CELL_WIDTH*6, CELL_HEIGHT*3), (CELL_WIDTH*6, CELL_HEIGHT*2)], [(CELL_WIDTH*7, CELL_HEIGHT*7), (CELL_WIDTH*7, CELL_HEIGHT*6), (CELL_WIDTH*7, CELL_HEIGHT*5), (CELL_WIDTH*7, CELL_HEIGHT*4), (CELL_WIDTH*7, CELL_HEIGHT*3), (CELL_WIDTH*7, CELL_HEIGHT*2)], [(CELL_WIDTH*8, CELL_HEIGHT*7), (CELL_WIDTH*8, CELL_HEIGHT*6), (CELL_WIDTH*8, CELL_HEIGHT*5), (CELL_WIDTH*8, CELL_HEIGHT*4), (CELL_WIDTH*8, CELL_HEIGHT*3), (CELL_WIDTH*8, CELL_HEIGHT*2)]]

# upload as surface icon image for the display screen
ICON_IMAGE = pygame.image.load("./assets/connect-four.png")

# set default framerate
FRAMERATE = 60

# set default coin color
COIN_COLOR_ONE = 'red'
COIN_COLOR_TWO = 'yellow'

# set default background color
BG_COLOR = 'gray'

